package digitallibrarymanagementsystem;


import javax.swing.JComboBox;

/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license

 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

 */
/**
 *
 * @author Asus
 */
public class Catagory extends javax.swing.JFrame {

    /**
     * Creates new form Catagory
     */
    public Catagory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    String choice;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        SelectionBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CategoryIcon = new javax.swing.JLabel();
        SustLogo = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        ExitButton = new com.k33ptoo.components.KButton();
        LoginButton = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(44, 83, 100));
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 32, 39));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectionBox.setBackground(new java.awt.Color(255, 255, 204));
        SelectionBox.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        SelectionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Student" }));
        SelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectionBoxActionPerformed(evt);
            }
        });
        kGradientPanel1.add(SelectionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 140, 30));
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 24, -1, -1));

        CategoryIcon.setBackground(new java.awt.Color(204, 204, 204));
        CategoryIcon.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CategoryIcon.setForeground(new java.awt.Color(255, 204, 204));
        CategoryIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\llll\\Statics.png")); // NOI18N
        CategoryIcon.setText("Cataegory");
        kGradientPanel1.add(CategoryIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 148, 54));

        SustLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\llll\\SUSTlogo.png")); // NOI18N
        kGradientPanel1.add(SustLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, 100));

        Header.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 204, 204));
        Header.setText("        WELLCOME TO IICT LIBRARY,SUST");
        kGradientPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 530, 60));

        ExitButton.setBorder(null);
        ExitButton.setText("Exit");
        ExitButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        ExitButton.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        ExitButton.setkBorderRadius(40);
        ExitButton.setkEndColor(new java.awt.Color(255, 0, 0));
        ExitButton.setkHoverEndColor(new java.awt.Color(255, 51, 51));
        ExitButton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        ExitButton.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        ExitButton.setkSelectedColor(new java.awt.Color(255, 0, 0));
        ExitButton.setkStartColor(new java.awt.Color(153, 0, 0));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 150, 40));

        LoginButton.setBorder(null);
        LoginButton.setText("Login");
        LoginButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        LoginButton.setkBorderRadius(40);
        LoginButton.setkEndColor(new java.awt.Color(0, 204, 0));
        LoginButton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        LoginButton.setkHoverStartColor(new java.awt.Color(0, 204, 0));
        LoginButton.setkPressedColor(new java.awt.Color(0, 204, 51));
        LoginButton.setkSelectedColor(new java.awt.Color(0, 0, 0));
        LoginButton.setkStartColor(new java.awt.Color(0, 204, 51));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 150, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 993, 555));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SelectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionBoxActionPerformed
        choice = (String) SelectionBox.getSelectedItem();
    }//GEN-LAST:event_SelectionBoxActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
              
        if( choice=="Admin"){
           //dispose();
          setVisible(false);
          new Login().setVisible(true);
        }
        else if( choice=="Student" ){
            dispose();
            new loginForStudent().setVisible(true);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catagory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryIcon;
    private com.k33ptoo.components.KButton ExitButton;
    private javax.swing.JLabel Header;
    private com.k33ptoo.components.KButton LoginButton;
    private javax.swing.JComboBox<String> SelectionBox;
    private javax.swing.JLabel SustLogo;
    private javax.swing.JLabel jLabel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
