/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitallibrarymanagementsystem;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Attribute.ID;
import java.sql.ResultSet;
import java.util.*;
import java.lang.String;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;

/**
 *
 * @author Asus
 */
public class FINE extends javax.swing.JFrame {
   String studentID;
    /**
     * Creates new form FINE
     */
    public FINE(String studentID) {
        this.studentID = studentID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        exit = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton2.setText("CALCULATE FINE");
        kButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        kButton2.setkBorderRadius(25);
        kButton2.setkEndColor(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverEndColor(new java.awt.Color(51, 204, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 51, 51));
        kButton2.setkStartColor(new java.awt.Color(0, 0, 102));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 380, 60));

        kButton4.setText("FIND FINE");
        kButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        kButton4.setkBorderRadius(25);
        kButton4.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(51, 204, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 204, 0));
        kButton4.setkStartColor(new java.awt.Color(0, 204, 0));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, 40));

        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setkBorderRadius(25);
        exit.setkEndColor(new java.awt.Color(204, 0, 0));
        exit.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        exit.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        exit.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        exit.setkStartColor(new java.awt.Color(204, 0, 0));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 180, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        Connection conn = null;
        String stid = studentID;
        
        System.out.println("id -> " + studentID);
        String sql = "SELECT * FROM `admin_data`";
        try {
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-dd");
            try ( Statement stmt = conn.createStatement();) {

                java.sql.ResultSet rs = stmt.executeQuery(sql);

                int flag = 0;
                while (rs.next()) {
                    String x = rs.getString("std_reg");
                    //String y = rs.getString("issue_date");
                    String joinDate = rs.getString("expired_date");
                    
                    System.out.println("x -> " + x + " | joindate -> " + joinDate);
                     

                    if (x.equals(stid)) {

                        LocalDate dateObj = LocalDate.now();
                        //dateObj=dateObj.plusDays(5);
                        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                        String LeaveDate = dateObj.format(formatter);
                        SimpleDateFormat obj = new SimpleDateFormat("yyyy-MM-dd");
                        Date date1 = obj.parse(joinDate);
                        Date date2 = obj.parse(LeaveDate);
                        System.out.println(date1 + "     " + date2);
                        long time_difference = date2.getTime() - date1.getTime();
                        long days_difference = (time_difference / (1000 * 60 * 60 * 24)) % 365;
                        System.out.println(days_difference);

                        if (days_difference > 0) {
                            long f = days_difference * 5;
                            JOptionPane.showMessageDialog(null, "Your total fine is"+"  "+f);
                            String q = "UPDATE `admin_data` SET fine=?  WHERE std_reg=?";
                            PreparedStatement st = conn.prepareStatement(q);
                            st.setInt(1, (int) f);
                    
                            st.setString(2, stid);
                            st.executeUpdate();
                            
                            q = "UPDATE `admin_data` SET status=? WHERE std_reg=?";
                            st = conn.prepareStatement(q);
                           
                            st.setString(1, "expired");
                            st.setString(2, stid);
                            st.executeUpdate();
                        } else {
                            JOptionPane.showMessageDialog(null, "You have no fine");
                         
                        }
                    }
                }

            }
        } catch (Exception e) {
            System.out.println("Statement probllem");
            e.printStackTrace();
        }        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        {
            setVisible(false);
            new StudentBookDetails(studentID).setVisible(true);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FINE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FINE("2019331097").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton exit;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
