/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitallibrarymanagementsystem;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.sql.ResultSet;
import java.util.*;
import java.lang.String;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Asus
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    
    String studentID;
    public IssueBook(String studentID) {
        this.studentID = studentID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        student = new javax.swing.JTextField();
        kButton3 = new com.k33ptoo.components.KButton();
        id = new javax.swing.JTextField();
        UserNameLabel = new com.k33ptoo.components.KButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 250));
        setMinimumSize(new java.awt.Dimension(850, 520));
        setSize(new java.awt.Dimension(850, 512));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 40, 90, 20));

        kGradientPanel2.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(993, 555));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton2.setText("Exit");
        kButton2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton2.setkBorderRadius(25);
        kButton2.setkEndColor(new java.awt.Color(204, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton2.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton2.setkStartColor(new java.awt.Color(255, 0, 0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 90, 30));

        kButton4.setText("Issue");
        kButton4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton4.setkBorderRadius(25);
        kButton4.setkEndColor(new java.awt.Color(51, 204, 0));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 153, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 204, 0));
        kButton4.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton4.setkStartColor(new java.awt.Color(51, 204, 0));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 90, 30));

        kButton5.setText("Student ID");
        kButton5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton5.setkBorderRadius(25);
        kButton5.setkEndColor(new java.awt.Color(102, 102, 102));
        kButton5.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton5.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton5.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 30));

        student.setBackground(new java.awt.Color(255, 255, 204));
        kGradientPanel2.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 260, 30));

        kButton3.setText("Book ID");
        kButton3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton3.setkBorderRadius(25);
        kButton3.setkEndColor(new java.awt.Color(102, 102, 102));
        kButton3.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton3.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton3.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 30));

        id.setBackground(new java.awt.Color(255, 255, 204));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        kGradientPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 260, 30));

        UserNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLabel.setBorder(null);
        UserNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UserNameLabel.setText("BOOK ISSUE");
        UserNameLabel.setEnabled(false);
        UserNameLabel.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        UserNameLabel.setkBorderRadius(30);
        UserNameLabel.setkEndColor(new java.awt.Color(0, 0, 102));
        UserNameLabel.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        UserNameLabel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        UserNameLabel.setkHoverStartColor(new java.awt.Color(51, 51, 255));
        UserNameLabel.setkStartColor(new java.awt.Color(0, 0, 255));
        UserNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameLabelActionPerformed(evt);
            }
        });
        kGradientPanel2.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 380, 30));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        setVisible(false);        // TODO add your handling code here:
        new StudentBookDetails(studentID).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed

        Connection conn = null, conn1 = null;

        String idd = id.getText();
        String stid = student.getText();
        //String namee = name.getText();
        String sql = "SELECT * FROM `book`";
        String sql1 = "SELECT * FROM `admin_data`";
        //System.out.println(sql);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //System.out.println("class loaded");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            // System.out.println("connection successful");
            try ( Statement stmt = conn.createStatement();) {
                // System.out.println("statement created....");
                Statement stmt1 = conn1.createStatement();
                java.sql.ResultSet rs = stmt.executeQuery(sql);
                ResultSet rs1 = (ResultSet) stmt1.executeQuery(sql1);
                String z = null;
                //System.out.println("query executed successfully");
                int flag = 0;
                while (rs.next()) {
                    String x = rs.getString("BookId");
                    String y = rs.getString("status");
                    z = rs.getString("BookName");

                    if (x.equals(idd) && y.equals("avail")) {
                        //JOptionPane.showMessageDialog(null, "Book issue successfully");
//                String q = "UPDATE detailst SET status=? WHERE BookId=?";
//                PreparedStatement st = conn.prepareStatement(q);
//                st.setString(1, "unavil");
//                st.setString(2, idd);
//                st.executeUpdate();conn.close();

                        //conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/addnewbook", "root", " ");
                        //System.out.println("Connection is created successfully:");
                        //setVisible(false);
                        flag = 1;
                        break;
                        //System.out.println("It works     ");
                    }
                    
                }
                if(flag==0)
                    {
                        JOptionPane.showMessageDialog(null, "Book doesn't exists");
                    }
                while (rs1.next() && flag==1) {
                    String x1 = rs1.getString("std_reg");

                    if (x1.equals(stid) && flag == 1) {
                        JOptionPane.showMessageDialog(null, "Book issue successfully");
                        String q = "UPDATE book SET status=? WHERE BookId=?";
                        PreparedStatement st = conn.prepareStatement(q);
                        st.setString(1, "unavil");
                        st.setString(2, idd);
                        st.executeUpdate();
                        q = "UPDATE admin_data SET BookId=? WHERE std_reg=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, idd);
                        st.setString(2, stid);
                        st.executeUpdate();
                        q = "UPDATE admin_data SET BookName=? WHERE std_reg=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, z);
                        st.setString(2, stid);
                        st.executeUpdate();
                        LocalDate dateObj = LocalDate.now();
                        //dateObj=dateObj.plusDays(5);
                        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                        String date = dateObj.format(formatter);
                        String q1 = "UPDATE `admin_data` SET issue_date=?  WHERE std_reg=?";
                        PreparedStatement st1 = conn1.prepareStatement(q1);
                        st1.setString(1, date);
                        st1.setString(2, stid);
                        st1.executeUpdate();
                        
                        dateObj=dateObj.plusDays(5);
                        formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                        date = dateObj.format(formatter);
                        q1 = "UPDATE `admin_data` SET expired_date=?  WHERE std_reg=?";
                        st1 = conn1.prepareStatement(q1);
                        st1.setString(1, date);
                        st1.setString(2, stid);
                        st1.executeUpdate();

                    }

                }
                if (flag == 0) {
                    JOptionPane.showMessageDialog(null, "Book doesn't exists");
                }
            }
        } catch (Exception e) {
            System.out.println("Statement probllem");
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    private void UserNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook("2019331063").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton UserNameLabel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField student;
    // End of variables declaration//GEN-END:variables
}
