package digitallibrarymanagementsystem;


import digitallibrarymanagementsystem.home;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
     //   setExtendedState(JFrame.MAXIMIZED_BOTH);
                
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        LoginButton = new com.k33ptoo.components.KButton();
        UserNameLabel = new com.k33ptoo.components.KButton();
        PasswordLabel = new com.k33ptoo.components.KButton();
        CloseButton = new com.k33ptoo.components.KButton();
        UserNameLabel1 = new com.k33ptoo.components.KButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setBorder(null);
        LoginButton.setForeground(new java.awt.Color(0, 0, 0));
        LoginButton.setText("login");
        LoginButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        LoginButton.setkBorderRadius(30);
        LoginButton.setkForeGround(new java.awt.Color(0, 0, 0));
        LoginButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        LoginButton.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        LoginButton.setkIndicatorColor(new java.awt.Color(0, 255, 0));
        LoginButton.setkStartColor(new java.awt.Color(0, 255, 0));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 100, 30));

        UserNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLabel.setBorder(null);
        UserNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UserNameLabel.setText("Sign in for Admin");
        UserNameLabel.setEnabled(false);
        UserNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        UserNameLabel.setkBorderRadius(30);
        UserNameLabel.setkEndColor(new java.awt.Color(51, 51, 255));
        UserNameLabel.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        UserNameLabel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        UserNameLabel.setkHoverStartColor(new java.awt.Color(51, 51, 255));
        UserNameLabel.setkStartColor(new java.awt.Color(0, 0, 255));
        UserNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameLabelActionPerformed(evt);
            }
        });
        kGradientPanel1.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 300, 30));

        PasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setBorder(null);
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Password");
        PasswordLabel.setEnabled(false);
        PasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        PasswordLabel.setkBorderRadius(30);
        PasswordLabel.setkEndColor(new java.awt.Color(255, 255, 255));
        PasswordLabel.setkForeGround(new java.awt.Color(0, 0, 0));
        PasswordLabel.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        PasswordLabel.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        PasswordLabel.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        PasswordLabel.setkStartColor(new java.awt.Color(255, 255, 255));
        PasswordLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordLabelActionPerformed(evt);
            }
        });
        kGradientPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 120, 30));

        CloseButton.setBackground(new java.awt.Color(0, 0, 0));
        CloseButton.setBorder(null);
        CloseButton.setForeground(new java.awt.Color(0, 0, 0));
        CloseButton.setText("Close");
        CloseButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        CloseButton.setkBorderRadius(30);
        CloseButton.setkEndColor(new java.awt.Color(255, 51, 51));
        CloseButton.setkForeGround(new java.awt.Color(0, 0, 0));
        CloseButton.setkHoverColor(new java.awt.Color(255, 51, 51));
        CloseButton.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        CloseButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        CloseButton.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        CloseButton.setkIndicatorColor(new java.awt.Color(255, 0, 0));
        CloseButton.setkStartColor(new java.awt.Color(255, 0, 0));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 100, 30));

        UserNameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLabel1.setBorder(null);
        UserNameLabel1.setForeground(new java.awt.Color(0, 0, 0));
        UserNameLabel1.setText("Username");
        UserNameLabel1.setEnabled(false);
        UserNameLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        UserNameLabel1.setkBorderRadius(30);
        UserNameLabel1.setkEndColor(new java.awt.Color(255, 255, 255));
        UserNameLabel1.setkForeGround(new java.awt.Color(0, 0, 0));
        UserNameLabel1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        UserNameLabel1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        UserNameLabel1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        UserNameLabel1.setkStartColor(new java.awt.Color(255, 255, 255));
        UserNameLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameLabel1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(UserNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 120, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jTextField1.setToolTipText("enter your name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 240, 30));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 204));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordField1.setToolTipText("enter your password");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 240, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
         
        //System.out.println("hjgjghgj1");
        
        if(jTextField1.getText().equals("Admin") && jPasswordField1.getText().equals("sust12"))
          {
              setVisible(false);
              new home().setVisible(true);
          }
          else 
          JOptionPane.showMessageDialog(null,"Invalid Username or Password");
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UserNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameLabelActionPerformed

    private void PasswordLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordLabelActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
 System.exit(0);  
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void UserNameLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameLabel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton CloseButton;
    private com.k33ptoo.components.KButton LoginButton;
    private com.k33ptoo.components.KButton PasswordLabel;
    private com.k33ptoo.components.KButton UserNameLabel;
    private com.k33ptoo.components.KButton UserNameLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
