/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitallibrarymanagementsystem;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class MyInformation extends javax.swing.JFrame {

    /**
     * Creates new form MyInformation
     */
    String studnetID;

    public MyInformation(String studnetID) {
        this.studnetID = studnetID;
        initComponents();
        showInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "std_reg", "username", "std_gmail", "DEPT", "session", "pass", "Book_Id", "Book_Name", "Issue_date", "Expired_date", "status", "fine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, 884, 267));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton4.setBorder(null);
        kButton4.setForeground(new java.awt.Color(51, 255, 255));
        kButton4.setText("Back");
        kButton4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        kButton4.setkBorderRadius(20);
        kButton4.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton4.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton4.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton4.setkIndicatorThickness(1000);
        kButton4.setkStartColor(new java.awt.Color(255, 0, 0));
        kButton4.setMaximumSize(new java.awt.Dimension(33, 10));
        kButton4.setMultiClickThreshhold(1L);
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("YOUR DATA");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 36, 280, 60));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        setVisible(false);
        new StudentBookDetails(studnetID).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void showInfo() {
        Connection conn = null;
        String stid = studnetID;
        String sql = "SELECT * FROM `admin_data`";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //System.out.println("class loaded");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            // System.out.println("connection successful");
            try ( Statement stmt = conn.createStatement();) {
                // System.out.println("statement created....");
                java.sql.ResultSet rs = stmt.executeQuery(sql);
                //System.out.println("query executed successfully");

                while (rs.next()) {

                    String x = rs.getString("std_reg");

                    if (x.equals(stid)) {

                        DefaultTableModel model = (DefaultTableModel) table.getModel();
                        model.setRowCount(0);

                        model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12)});

                    }
                }

            }
        } catch (Exception e) {
            System.out.println("Statement probllem");
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyInformation("2017331063").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
