/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitallibrarymanagementsystem;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import static javax.swing.text.html.HTML.Attribute.ID;
/**
 *
 * @author Asus
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    
    String studentID;
    public ReturnBook(String studentID) {
        this.studentID = studentID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idd = new javax.swing.JTextField();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        save = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idd.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 214, 335, 34));

        kButton2.setText("Return Book");
        kButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        kButton2.setkBorderRadius(25);
        kButton2.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(51, 51, 18));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 51, 51));
        kButton2.setkStartColor(new java.awt.Color(255, 0, 0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 420, 40));

        kButton3.setBackground(new java.awt.Color(204, 255, 255));
        kButton3.setForeground(new java.awt.Color(0, 0, 0));
        kButton3.setText("Book ID");
        kButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        kButton3.setkBorderRadius(25);
        kButton3.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(51, 51, 18));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 51, 51));
        kButton3.setkStartColor(new java.awt.Color(204, 255, 204));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 210, 40));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setText("Return");
        save.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        save.setkBorderRadius(25);
        save.setkEndColor(new java.awt.Color(0, 153, 51));
        save.setkHoverEndColor(new java.awt.Color(51, 51, 18));
        save.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        save.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        save.setkSelectedColor(new java.awt.Color(0, 0, 0));
        save.setkStartColor(new java.awt.Color(51, 204, 0));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        kGradientPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 110, 40));

        kButton1.setText("Back");
        kButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        kButton1.setkBorderRadius(25);
        kButton1.setkEndColor(new java.awt.Color(51, 0, 51));
        kButton1.setkHoverEndColor(new java.awt.Color(51, 51, 18));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 51, 0));
        kButton1.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton1.setkStartColor(new java.awt.Color(204, 0, 0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 100, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 860, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
             setVisible(false);   // TODO add your handling code here:
            new StudentBookDetails(studentID).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         Connection conn =null;
        String ID = idd.getText();
        String sql = "SELECT * FROM `book`";
        System.out.println(sql);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("class loaded");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            System.out.println("connection successful");
            try ( Statement stmt = conn.createStatement();) {
                System.out.println("statement created....");
                java.sql.ResultSet rs = stmt.executeQuery(sql);
                System.out.println("query executed successfully");
                int flag=0;
                while (rs.next()) {
                    String x = rs.getString("BookId");
                    String y = rs.getString("status");
                    if (x.equals(ID) && y.equals("unavil")) {
                        JOptionPane.showMessageDialog(null, "Book return successfully");
                        String q = "UPDATE book SET status=? WHERE BookId=?";
                        PreparedStatement st = conn.prepareStatement(q);
                        st.setString(1, "avail");
                        st.setString(2, ID);
                        st.executeUpdate();
                        
                        //conn.close();

                        //                   conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/addnewbook", "root", " ");
                        //                   System.out.println("Connection is created successfully:");
                        //
                        //                       setVisible(false);
                        flag=1;
                    }
                }
                if(flag==0){
                    JOptionPane.showMessageDialog(null, "Invalid,BookId");
                }
                else
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    System.out.println("class loaded");
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
                System.out.println("connection successful");
            try ( Statement stmt1 = conn.createStatement();) {
                System.out.println("statement created....");
                sql = "SELECT * FROM `admin_data`";
                rs = stmt.executeQuery(sql);
                System.out.println("query executed successfully");
                //while (rs.next()) {
                        
                        //String y = rs.getString("status");
                   
                        
                        String q = "UPDATE admin_data SET BookName=? WHERE BookId=?";
                        PreparedStatement st = conn.prepareStatement(q);
                        st.setString(1, "NULL");
                        st.setString(2, ID);
                        st.executeUpdate();
                        q = "UPDATE admin_data SET issue_date=? WHERE BookId=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, "NULL");
                        st.setString(2, ID);
                        st.executeUpdate();
                        q = "UPDATE admin_data SET expired_date=? WHERE BookId=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, "NULL");
                        st.setString(2, ID);
                        st.executeUpdate();
                        
                        q = "UPDATE admin_data SET status=? WHERE BookId=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, "NULL");
                        st.setString(2, ID);
                        st.executeUpdate();
                        
                        q = "UPDATE admin_data SET fine=? WHERE BookId=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, "NULL");
                        st.setString(2, ID);
                        st.executeUpdate();
                        
                        String xx = ID;
                        q = "UPDATE admin_data SET BookId=? WHERE BookId=?";
                        st = conn.prepareStatement(q);
                        st.setString(1, "NULL");
                        st.setString(2, xx);
                        st.executeUpdate();
                        
                        //conn.close();

                        //                   conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/addnewbook", "root", " ");
                        //                   System.out.println("Connection is created successfully:");
                        //
                        //                       setVisible(false);
                        flag=1;
                    
                //}
                }
            }
        }
        }catch (Exception e) {
            System.out.println("Statement probllem");
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook("2017331063").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idd;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton save;
    // End of variables declaration//GEN-END:variables
}
