/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitallibrarymanagementsystem;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Attribute.ID;
/**
 *
 * @author Asus
 */


public class SearchBook extends javax.swing.JFrame {

    /**
     * Creates new form SearchBook
     */
        
    String studentID;
    
    public SearchBook(String studentID) {
        this.studentID = studentID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        kButton4 = new com.k33ptoo.components.KButton();
        find = new com.k33ptoo.components.KButton();
        Exit = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setAlignmentX(0.0F);
        kGradientPanel1.setAlignmentY(0.0F);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 0));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 153));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 118, 72, -1));
        kGradientPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 310, 40));
        kGradientPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 310, 40));

        kButton4.setBorder(null);
        kButton4.setForeground(new java.awt.Color(51, 255, 255));
        kButton4.setText("Search Book");
        kButton4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        kButton4.setkBorderRadius(20);
        kButton4.setkEndColor(new java.awt.Color(0, 102, 102));
        kButton4.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton4.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(51, 51, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton4.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton4.setkIndicatorThickness(1000);
        kButton4.setkStartColor(new java.awt.Color(153, 153, 0));
        kButton4.setMaximumSize(new java.awt.Dimension(33, 10));
        kButton4.setMultiClickThreshhold(1L);
        kGradientPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 460, 40));

        find.setBorder(null);
        find.setForeground(new java.awt.Color(51, 255, 255));
        find.setText("Find");
        find.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        find.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        find.setkBorderRadius(40);
        find.setkEndColor(new java.awt.Color(0, 51, 51));
        find.setkHoverColor(new java.awt.Color(0, 153, 0));
        find.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        find.setkHoverForeGround(new java.awt.Color(51, 51, 0));
        find.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        find.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        find.setkIndicatorThickness(1000);
        find.setkStartColor(new java.awt.Color(51, 204, 0));
        find.setMaximumSize(new java.awt.Dimension(33, 10));
        find.setMultiClickThreshhold(1L);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        kGradientPanel1.add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 120, 40));

        Exit.setBorder(null);
        Exit.setForeground(new java.awt.Color(51, 255, 255));
        Exit.setText("Exit");
        Exit.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Exit.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        Exit.setkBorderRadius(40);
        Exit.setkEndColor(new java.awt.Color(255, 0, 0));
        Exit.setkHoverColor(new java.awt.Color(255, 255, 102));
        Exit.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        Exit.setkHoverForeGround(new java.awt.Color(51, 51, 0));
        Exit.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Exit.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        Exit.setkIndicatorThickness(1000);
        Exit.setkStartColor(new java.awt.Color(204, 0, 0));
        Exit.setMaximumSize(new java.awt.Dimension(33, 10));
        Exit.setMultiClickThreshhold(1L);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 120, 40));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton5.setBorder(null);
        kButton5.setForeground(new java.awt.Color(51, 255, 255));
        kButton5.setText("BOOK ID");
        kButton5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        kButton5.setkBorderRadius(20);
        kButton5.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton5.setkHoverColor(new java.awt.Color(51, 51, 51));
        kButton5.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        kButton5.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        kButton5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton5.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton5.setkIndicatorThickness(1000);
        kButton5.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton5.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton5.setMaximumSize(new java.awt.Dimension(33, 10));
        kButton5.setMultiClickThreshhold(1L);
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 180, 40));

        kButton7.setBorder(null);
        kButton7.setForeground(new java.awt.Color(51, 255, 255));
        kButton7.setText("BOOKNAME");
        kButton7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        kButton7.setkBorderRadius(20);
        kButton7.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton7.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton7.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        kButton7.setkHoverForeGround(new java.awt.Color(51, 51, 0));
        kButton7.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton7.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton7.setkIndicatorThickness(1000);
        kButton7.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton7.setMaximumSize(new java.awt.Dimension(33, 10));
        kButton7.setMultiClickThreshhold(1L);
        kGradientPanel2.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, 40));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        kButton6.setBorder(null);
        kButton6.setForeground(new java.awt.Color(51, 255, 255));
        kButton6.setText("BOOKNAME");
        kButton6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(255, 255, 102));
        kButton6.setkBorderRadius(20);
        kButton6.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton6.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton6.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        kButton6.setkHoverForeGround(new java.awt.Color(51, 51, 0));
        kButton6.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton6.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton6.setkIndicatorThickness(1000);
        kButton6.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton6.setMaximumSize(new java.awt.Dimension(33, 10));
        kButton6.setMultiClickThreshhold(1L);
        kGradientPanel1.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 860, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        Connection conn = null;

        String name = jTextField1.getText();
        String idd = jTextField2.getText();
        String sql = "SELECT * FROM `book`";
        System.out.println(sql);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //System.out.println("class loaded");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            // System.out.println("connection successful");
            try ( Statement stmt = conn.createStatement();) {
                // System.out.println("statement created....");
                java.sql.ResultSet rs = stmt.executeQuery(sql);
                //System.out.println("query executed successfully");
                int flag=0;
                while (rs.next()) {

                    String x = rs.getString("BookName");
                    String y = rs.getString("BookId");
                    String z = rs.getString("status");
                    if ((x.equals(name) || y.equals(idd)) && z.equals("avail")) {
                        JOptionPane.showMessageDialog(null, "Book is available");
                        flag=1;
                        break;
                    }
                }
                if(flag==0){
                    JOptionPane.showMessageDialog(null, "Book doesn't exists");
                }
            }
        } catch (Exception e) {
            System.out.println("Statement probllem");
            e.printStackTrace();
        }
    }//GEN-LAST:event_findActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        setVisible(false);
        new StudentBookDetails(studentID).setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBook("2019331063").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Exit;
    private com.k33ptoo.components.KButton find;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
