package digitallibrarymanagementsystem;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Attribute.ID;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class SignUpPage extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        exit = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        studentIdTextField = new javax.swing.JTextField();
        depertmentCombobox = new javax.swing.JComboBox<>();
        sessionCombobox = new javax.swing.JComboBox<>();
        passwordTextfield = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        gmail = new javax.swing.JTextField();
        kButton8 = new com.k33ptoo.components.KButton();
        usernameTextField = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setkBorderRadius(25);
        exit.setkEndColor(new java.awt.Color(204, 0, 0));
        exit.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        exit.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        exit.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        exit.setkStartColor(new java.awt.Color(204, 0, 0));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 100, 30));

        kButton2.setText("Sign Up");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kButton2.setkBorderRadius(25);
        kButton2.setkEndColor(new java.awt.Color(0, 204, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(0, 204, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 204, 0));
        kButton2.setkSelectedColor(new java.awt.Color(0, 204, 0));
        kButton2.setkStartColor(new java.awt.Color(0, 153, 51));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 100, 30));

        studentIdTextField.setBackground(new java.awt.Color(255, 204, 204));
        studentIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(studentIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 270, 30));

        depertmentCombobox.setBackground(new java.awt.Color(255, 204, 204));
        depertmentCombobox.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        depertmentCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depertment", "CSE", "SWE", "EEE" }));
        depertmentCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depertmentComboboxActionPerformed(evt);
            }
        });
        kGradientPanel1.add(depertmentCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 255, 270, 30));

        sessionCombobox.setBackground(new java.awt.Color(255, 255, 204));
        sessionCombobox.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sessionCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2017-18", "2018-19", "2019-20", "2020-21" }));
        sessionCombobox.setToolTipText("");
        sessionCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionComboboxActionPerformed(evt);
            }
        });
        kGradientPanel1.add(sessionCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 315, 270, 30));

        passwordTextfield.setBackground(new java.awt.Color(255, 255, 204));
        passwordTextfield.setToolTipText("enter your password");
        passwordTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextfieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(passwordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("Sign Up");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 150, 40));

        kButton3.setText("Username");
        kButton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kButton3.setkBorderRadius(39);
        kButton3.setkEndColor(new java.awt.Color(0, 0, 51));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 0, 51));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 204));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton3.setkIndicatorThickness(5);
        kButton3.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 30));

        kButton4.setText("Department ");
        kButton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kButton4.setkBorderRadius(39);
        kButton4.setkEndColor(new java.awt.Color(0, 0, 51));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 0, 51));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton4.setkIndicatorThickness(5);
        kButton4.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 30));

        kButton5.setText("Session");
        kButton5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kButton5.setkBorderRadius(39);
        kButton5.setkEndColor(new java.awt.Color(0, 0, 51));
        kButton5.setkHoverEndColor(new java.awt.Color(0, 0, 51));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton5.setkIndicatorThickness(5);
        kButton5.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, 30));

        kButton6.setText("Password");
        kButton6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kButton6.setkBorderRadius(39);
        kButton6.setkEndColor(new java.awt.Color(0, 0, 51));
        kButton6.setkHoverEndColor(new java.awt.Color(0, 0, 51));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(0, 0, 51));
        kButton6.setkIndicatorThickness(5);
        kButton6.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 30));

        kButton7.setText("Student ID");
        kButton7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        kButton7.setkBorderRadius(39);
        kButton7.setkEndColor(new java.awt.Color(0, 0, 51));
        kButton7.setkHoverEndColor(new java.awt.Color(0, 0, 51));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton7.setkHoverStartColor(new java.awt.Color(0, 0, 51));
        kButton7.setkIndicatorThickness(5);
        kButton7.setkPressedColor(new java.awt.Color(0, 0, 0));
        kButton7.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton7.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 30));

        gmail.setBackground(new java.awt.Color(255, 204, 204));
        gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailActionPerformed(evt);
            }
        });
        kGradientPanel1.add(gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 270, 30));

        kButton8.setText("Gmail ID");
        kButton8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        kButton8.setkBackGroundColor(new java.awt.Color(0, 0, 51));
        kButton8.setkBorderRadius(39);
        kButton8.setkEndColor(new java.awt.Color(0, 0, 51));
        kButton8.setkHoverEndColor(new java.awt.Color(0, 0, 51));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton8.setkIndicatorThickness(5);
        kButton8.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 30));

        usernameTextField.setBackground(new java.awt.Color(255, 204, 204));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 270, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 950, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String choice;
    private void depertmentComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depertmentComboboxActionPerformed
        choice = (String) depertmentCombobox.getSelectedItem();
    }//GEN-LAST:event_depertmentComboboxActionPerformed

    private void sessionComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionComboboxActionPerformed
        choice = (String) sessionCombobox.getSelectedItem();

    }//GEN-LAST:event_sessionComboboxActionPerformed

    private void passwordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextfieldActionPerformed

    }//GEN-LAST:event_passwordTextfieldActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        {
            setVisible(false);
            new loginForStudent().setVisible(true);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        /*setVisible(false);
              new StudentBookDetails().setVisible(true);*/
//          setVisible(false);
//            new loginForStudent().setVisible(true);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("class lodded successfully"
                    + "");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/digital_library", "root", "");
            System.out.println("Connection created");
//          String query = "INSERT INTO signup-page VALUES ('?','?','?','?','?')";
            String query = "INSERT INTO `admin_data`(std_reg, username,std_gmail, dept, session, pass) VALUES (" + studentIdTextField.getText()
                    + ",\"" + usernameTextField.getText() + "\", \"" + gmail.getText()+ "\", \"" +depertmentCombobox.getSelectedItem() + "\" ,\""
                    + sessionCombobox.getSelectedItem() + "\",\"" + passwordTextfield.getText() + "\")";

            System.out.println("query -> " + query);

            Statement stm = con.createStatement();
            stm.execute(query);
            System.out.println("query executed succesfully");
//               pst = con.prepareStatement(query);
//               pst.setString(1,ID.getText());
//             pst.setString(2,username.getText());
//             pst.setString(3,DEPT.getSelectedItem().toString());
//             pst.setString(4,SESSION.getSelectedItem().toString());
//             pst.setString(5,PASS.getText());
//             pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "registered ");
        } catch (Exception e) {
            System.out.println("couldn't load class");
            e.printStackTrace();
        }

    }//GEN-LAST:event_kButton2ActionPerformed

    private void studentIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTextFieldActionPerformed

    private void gmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton8ActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> depertmentCombobox;
    private com.k33ptoo.components.KButton exit;
    private javax.swing.JTextField gmail;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField passwordTextfield;
    private javax.swing.JComboBox<String> sessionCombobox;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
