package digitallibrarymanagementsystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class StudentBookDetails extends javax.swing.JFrame {

    /**
     * Creates new form StudentBookDetails
     */
    String studentID;
    public StudentBookDetails(String studentID) {
        this.studentID = studentID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        fine = new com.k33ptoo.components.KButton();
        Return_book = new com.k33ptoo.components.KButton();
        search_book = new com.k33ptoo.components.KButton();
        issueBook = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fine.setBackground(new java.awt.Color(204, 204, 204));
        fine.setBorder(null);
        fine.setText("Total Fine");
        fine.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        fine.setkBackGroundColor(new java.awt.Color(255, 204, 51));
        fine.setkBorderRadius(35);
        fine.setkEndColor(new java.awt.Color(51, 51, 51));
        fine.setkHoverForeGround(new java.awt.Color(255, 255, 204));
        fine.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        fine.setkSelectedColor(new java.awt.Color(51, 51, 51));
        fine.setkStartColor(new java.awt.Color(102, 0, 102));
        fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineActionPerformed(evt);
            }
        });
        kGradientPanel1.add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, -1));

        Return_book.setBackground(new java.awt.Color(204, 204, 204));
        Return_book.setBorder(null);
        Return_book.setText("Return Book");
        Return_book.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Return_book.setkBackGroundColor(new java.awt.Color(255, 204, 51));
        Return_book.setkBorderRadius(35);
        Return_book.setkEndColor(new java.awt.Color(51, 51, 51));
        Return_book.setkHoverForeGround(new java.awt.Color(255, 255, 204));
        Return_book.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Return_book.setkSelectedColor(new java.awt.Color(51, 51, 51));
        Return_book.setkStartColor(new java.awt.Color(51, 51, 0));
        Return_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_bookActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Return_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, -1));

        search_book.setBackground(new java.awt.Color(204, 204, 204));
        search_book.setBorder(null);
        search_book.setText("Search Book");
        search_book.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        search_book.setkBackGroundColor(new java.awt.Color(255, 204, 51));
        search_book.setkBorderRadius(35);
        search_book.setkEndColor(new java.awt.Color(0, 0, 0));
        search_book.setkHoverForeGround(new java.awt.Color(255, 255, 204));
        search_book.setkHoverStartColor(new java.awt.Color(255, 51, 102));
        search_book.setkSelectedColor(new java.awt.Color(51, 51, 51));
        search_book.setkStartColor(new java.awt.Color(255, 0, 0));
        search_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bookActionPerformed(evt);
            }
        });
        kGradientPanel1.add(search_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, -1));

        issueBook.setBorder(null);
        issueBook.setForeground(new java.awt.Color(255, 255, 204));
        issueBook.setText("Issue Book");
        issueBook.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        issueBook.setkBackGroundColor(new java.awt.Color(153, 0, 51));
        issueBook.setkBorderRadius(25);
        issueBook.setkEndColor(new java.awt.Color(0, 0, 0));
        issueBook.setkHoverColor(new java.awt.Color(0, 0, 0));
        issueBook.setkHoverForeGround(new java.awt.Color(255, 153, 0));
        issueBook.setkHoverStartColor(new java.awt.Color(255, 51, 0));
        issueBook.setkStartColor(new java.awt.Color(204, 102, 0));
        issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookActionPerformed(evt);
            }
        });
        kGradientPanel1.add(issueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, -1));

        kButton2.setText("Statitics");
        kButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        kButton2.setkBorderRadius(25);
        kButton2.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(51, 51, 18));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 51, 51));
        kButton2.setkStartColor(new java.awt.Color(51, 51, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 40));

        kButton3.setText("Your Data");
        kButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        kButton3.setkBorderRadius(25);
        kButton3.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(51, 51, 18));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 51, 51));
        kButton3.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 210, 40));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\llll\\exit.png")); // NOI18N
        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bookActionPerformed
               setVisible(false);
               new SearchBook(studentID).setVisible(true);                
    }//GEN-LAST:event_search_bookActionPerformed

    private void Return_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_bookActionPerformed
       setVisible(false);
       new ReturnBook(studentID).setVisible(true);
    }//GEN-LAST:event_Return_bookActionPerformed

    private void issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookActionPerformed
               setVisible(false);
               new IssueBook(studentID).setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_issueBookActionPerformed

    private void fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineActionPerformed
           setVisible(false);
           new FINE(studentID).setVisible(true);
    }//GEN-LAST:event_fineActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
 setVisible(false);
        new DisplayData(studentID).setVisible(true);
           // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
       setVisible(false);
       new MyInformation(studentID).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        setVisible(false);
        new Catagory().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentBookDetails("2017331063").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Return_book;
    private com.k33ptoo.components.KButton fine;
    private com.k33ptoo.components.KButton issueBook;
    private javax.swing.JButton jButton6;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton search_book;
    // End of variables declaration//GEN-END:variables
}
